services:
  postgres:
    image: postgres:15
    container_name: barbershop_postgres
    restart: always
    environment:
      POSTGRES_USER: hy
      POSTGRES_PASSWORD_FILE: /run/secrets/db_password
      POSTGRES_DB: barbershop_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    secrets:
      - db_password

  nestjs:
    build: .
    container_name: barbershop_nestjs
    restart: always
    ports:
      - "5000:5000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_ACCESS_EXPIRES_IN: ${JWT_ACCESS_EXPIRES_IN}
      JWT_REFRESH_EXPIRES_IN: ${JWT_REFRESH_EXPIRES_IN}
      PORT: ${PORT}
      NODE_ENV: ${NODE_ENV}
    depends_on:
      - postgres

secrets:
  db_password:
    external: true

volumes:
  postgres_data:
