services:
  postgres:
    image: postgres:16
    container_name: hyco_postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - hyco_network

  backend:
    build: .
    container_name: hyco_backend
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres
    networks:
      - hyco_network
    expose:
      - "5000"
    volumes:
      - uploads:/var/www/barbershop_uploads

  nginx:
    image: nginx:alpine
    container_name: hyco_nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - uploads:/var/www/barbershop_uploads:ro
    depends_on:
      - backend
    networks:
      - hyco_network

  prisma_studio:
    image: barbershop-backend
    container_name: hyco_prisma_studio
    environment:
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "5555:5555"
    command: npx prisma studio --browser none --port 5555
    networks:
      - hyco_network


volumes:
  postgres_data:
  uploads:

networks:
  hyco_network:
