services:
  postgres:
    image: postgres:15
    container_name: barbershop_postgres
    restart: always
    environment:
      POSTGRES_USER: hy
      POSTGRES_PASSWORD: updown2Oo
      POSTGRES_DB: barbershop_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  nestjs:
    build: .
    container_name: barbershop_nestjs
    restart: always
    env_file:
      - .env
    ports:
      - "5000:5000"
    depends_on:
      - postgres

volumes:
  postgres_data:
